### ISSUE TITLE
Redirect requests to leader

### ISSUE THREAD

**Issue by ShiKaiWi** [CeresDB/ceresmeta#18]
**Description**
The cluster of ceresmeta provides service as a whole for ceresdb nodes, that is to say, one request can be received by any ceresmeta instance.
However, some service, e.g. ID generator, actually can only be provided by the leader. So the followers must can redirect the traffic into the leaders for requests of specific types.

**Proposal**
(TODO)

**Additional context**

**Comment by waynexia** [comment]
Should meta client keep the info (route table) about the current leader?

If it does, should we implement the same logic (distinguish operations) in meta client as well?
