### ISSUE TITLE
Fmt check failed in go 1.19

### ISSUE THREAD

**Issue by Rachelint** [CeresDB/ceresmeta#49]
**Describe this problem**

Make build failed due to fmt check in go 1.19.

**Steps to reproduce**

+ Install go 1.19.
+ Try to build.

**Expected behavior**

Build success.

**Additional Information**

**Comment by ShiKaiWi** [comment]
I figure it out that it is an enhancement for `gofmt` introduced by [go1.19](https://tip.golang.org/doc/go1.19) that causes the `make check` failed.:
> Go 1.19 adds support for links, lists, and clearer headings in doc comments. As part of this change, [gofmt](https://tip.golang.org/cmd/gofmt) now reformats doc comments to make their rendered meaning clearer. See “[Go Doc Comments](https://tip.golang.org/doc/comment)” for syntax details and descriptions of common mistakes now highlighted by gofmt. As another part of this change, the new package [go/doc/comment](https://tip.golang.org/pkg/go/doc/comment/) provides parsing and reformatting of doc comments as well as support for rendering them to HTML, Markdown, and text.

**Comment by ShiKaiWi** [comment]
I will fix these comments, and upgrade to go1.19.
